swipe:
  3:
    left:
      command: 'xdotool key alt+Left'
    right:
      command: 'xdotool key alt+Right'
pinch:
  in:
    command: 'xdotool keydown ctrl click 4 click 4 keyup ctrl'
  out:
    command: 'xdotool keydown ctrl click 5 click 5 keyup ctrl'

